### ISSUE TITLE
Move pid file to /var/run

### ISSUE THREAD

**Issue by linc01n** [bflad/chef-stash#100]
We should move the `/opt/atlassian/stash/work/catalina.pid` to `/var/run`

It is because we are symlinking `/opt/atlassian/stash` to the latest version of stash. Every time we run the chef script to upgrade stash, it will change the symlink target and failed the stash restart since the service can't find the pid.

So the situation is like this:

`/opt/atlassian/stash` -> `/opt/atlassian/stash-3.9.0`
the `catalina.pid`  is located in `/opt/atlassian/stash-3.9.0`

We run the cookbooks to update stash, now it points to 
`/opt/atlassian/stash` -> `/opt/atlassian/stash-3.10.0`
the `catalina.pid`  is still located in `/opt/atlassian/stash-3.9.0`

At the end of cookbook, we restart the stash service. But it fails because it can't find `/opt/atlassian/stash-3.10.0/work/catalina.pid`

reference: http://stackoverflow.com/questions/5173636/must-my-pidfile-be-located-in-var-run

**Comment by legal90** [comment]
:+1:

**Comment by bflad** [comment]
:+1:

**Comment by l4u** [comment]
:+1:

**Comment by patcon** [comment]
I think this can be closed now?

**Comment by linc01n** [comment]
I didn't merge to master. So I leave this open until `4.0` released.

**Comment by patcon** [comment]
Ah ok, gotcha :) I don't normally see cookbooks using release branches, and hadn't realized.

**Comment by linc01n** [comment]
`4.0` will contain breaking changes so we put it into a separate branch now. Mainly this one

4.0.0 (When Released)
Enhancement: #49: Update default database to postgresql

I am not sure how not to break other people deployment with the new cookbook.

**Comment by patcon** [comment]
One possibility might be to have complex logic in the cookbook until a major release (to support all use-cases), but then make it known (via chef run warnings, etc) that the attributes or approaches will be deprecated in X amount of time?

**Comment by linc01n** [comment]
Maybe we check if the user installed mysql then use the mysql path?

**Comment by patcon** [comment]
Hm. You mean check the run list?

I think the way I've seen is to do some sort of "responds_to?" ruby check on a resource, to check on a feature that would only exist in cookbook version X but not in cookbook version Y. (I don't think we can add conditional logic based on "what version of mysql cookbook is being used"... although I may be wrong)

**Comment by patcon** [comment]
Example: http://jtimberman.housepub.org/blog/2015/03/20/chef-gem-compile-time-compatibility/

**Comment by linc01n** [comment]
Merged!
