### ISSUE TITLE
Need any new co-maintainers?

### ISSUE THREAD

**Issue by patcon** [bflad/chef-stash#106]
No pressure. Just curious. I prefer to operate within a process where nothing gets merged until there's a +1 vote of confidence from a co-maintainer, so you wouldn't have to worry about me going overboard :)

(And fwiw, in case you're looking at my PR's and not liking them, I'll admit that I tend to be way more liberal with my PR's changes when I'm not the maintainer. When I am a maintainer, I feel less pressure to get multiple things into single PR's, as I can merge my own individual ones once +1's have been given)

**Comment by linc01n** [comment]
I am thinking we need a process if we have more than 1 maintainer in this project. I like the +1 approach. 

@bflad Would you mind adding one more maintainer to this project?

**Comment by patcon** [comment]
Hey @bflad, I think I'm going to need push access in order to get #108 working, if you have a sec to consider

**Comment by bflad** [comment]
I have granted @patcon push access just now. Thank you both!

**Comment by patcon** [comment]
Thanks a bunch!
