### ISSUE TITLE
make create directory recursive

### ISSUE THREAD

**Issue by ramonskie** [bflad/chef-stash#117]
when you can provide the path
for example 
``
default[:stash][:backup_client][:backup_path] = '/tmp/backups/stash-backup/'
``
then you should be able to do this this is now not possible
because the recursive options is not set
https://github.com/bflad/chef-stash/blob/master/recipes/backup_client.rb#L31

**Comment by linc01n** [comment]
Thanks @ramonskie 

I think the recursive flag is never set to `true`

Going to add that in.
