### ISSUE TITLE
Support Bitbucket 4.6

### ISSUE THREAD

**Issue by atikhono** [bflad/chef-stash#153]
Hi,

Bitbucket 4.6. has been released and finally code search is here!
Also includes some useful feature like personalised timezones, blame in diifs, etc.
More in release notes: https://confluence.atlassian.com/bitbucketserver/bitbucket-server-4-6-release-notes-827109988.html.

Please add Bitbucket 4.6 to the cookbook.

**Comment by linc01n** [comment]
Oh! nice! and last modified date of file finally bake into the file browser. Let me work on this now!

**Comment by linc01n** [comment]
Updated in #154
