### ISSUE TITLE
Code search is not working in 4.6.0

### ISSUE THREAD

**Issue by linc01n** [bflad/chef-stash#156]
There are 2 new export variable scripts in `4.6.0`
`bin/set-bitbucket-home.sh` and `bin/set-bitbucket-user.sh`

**Comment by linc01n** [comment]
Beside this, there is a new proxy rule for apache reverse proxy. And default elasticsearch username and password need to add.

**Comment by linc01n** [comment]
I have a question about this part:
<img width="807" alt="screen shot 2016-05-14 at 3 58 05 pm" src="https://cloud.githubusercontent.com/assets/667272/15267173/b2f39ce2-19ec-11e6-985d-6e5d02afc6e6.png">

Should I set the username and password in `bitbucket.properties` ?
Or let the user input them?

/cc @bflad @legal90

**Comment by legal90** [comment]
@linc01n I would leave the built-in Elasticsearch instance by default. 
It's nice to have a possibility to configure an external instance, but it should be optional, IMO.

**Comment by atikhono** [comment]
@linc01n You don't need to add credentials for the bundled elasticsearch instance. Please review my pull request for set-bitbucket-home/user.sh #157
