### ISSUE TITLE
Discussion: change default database to PostgreSQL?

### ISSUE THREAD

**Issue by bflad** [bflad/chef-stash#49]
Up for discussion for next major release of the cookbook, but please see note at top of MySQL/MariaDB integration page: https://confluence.atlassian.com/display/STASH/Connecting+Stash+to+MySQL

Of course you can always keep using MySQL by setting the necessary database attributes/data bag items.

> MySQL and MariaDB, while supported by Stash Server, are currently not recommended especially in larger instances, due to inherent performance and deadlock issues that occur in this database engine under heavy load.
> 
> Affected systems may experience slow response times, deadlock errors and in extreme cases errors due to running out of database connections. These issues are intrinsic to MySQL and MariaDB (no other database engine in Stash's Supported platforms shares this behavior) and are due to the way MySQL and MariaDB perform row-level locking in transactions. See http://dev.mysql.com/doc/refman/5.0/en/innodb-deadlocks.html for some general information on this.
> 
> Stash Server does its best to work around the MySQL / MariaDB behavior - see issues STASH-4517, STASH-4701 and others for example. However, under very heavy load you will generally get better performance with any of the other database engines supported by Stash (such as PostgreSQL which is also freely available) than you will with MySQL or MariaDB. Please see Connecting Stash to an external database for instructions on migrating your data to one of these other engines.

**Comment by legal90** [comment]
Yes, I think it's reasonable to use PostgreSQL by default in this cookbook. 

By the way, I'm using PostgreSQL in my installation as well.

**Comment by linc01n** [comment]
I :+1: changing the default to postgresql.
 

I am using postgresql for my production stash as well.

**Comment by mrjcleaver** [comment]
+1

**Comment by patcon** [comment]
+1

**Comment by legal90** [comment]
It was done in https://github.com/bflad/chef-stash/pull/128. So, the request could be closed (cc: @linc01n )

**Comment by linc01n** [comment]
Yes. Starting from `4.0.0`, the default database is set to postgreSQL
