### ISSUE TITLE
cookbook is broker because of no versionlock in metadata

### ISSUE THREAD

**Issue by ramonskie** [bflad/chef-stash#55]
because there is no version lock in the meta data

and mysql and database have had some major overhaul
it does not work anymore

this can be fixed by setting the depend versions in the metadata
```
depends 'mysql',              '~> 3.0.12'
depends 'database',           '~> 1.5.2'
```

or use the latest mysql/datbaase cookbook (this require some small adjustments)
as i have done in https://github.com/ramonskie/bamboo/commit/5cbd9d03031ea5f6f0f07a6cbbcd5abf3f47d7a1

**Comment by bflad** [comment]
Definitely sounds like a great idea. I think I'll lock to working mysql/database/postgresql versions in 3.x of the cookbook and create an issue to upgrade to latest versions for 4.x of the cookbook.
