### ISSUE TITLE
Support for Stash DIY backup - maybe?

### ISSUE THREAD

**Issue by iiro** [bflad/chef-stash#63]
Hi,

have you noticed this one: https://confluence.atlassian.com/display/STASH/Using+Stash+DIY+Backup?

We're using the Atlassian's example to do (practically) online backups from Stash - as we want to keep our repos online as much as possible.

Just letting you know about this if you would see it beneficial too in your cookbook setup (and maybe in your setup).

PS. Excellent stuff you have done! :) :)

**Comment by legal90** [comment]
I'm going to implement it soon and will send a pull request here.

As I see, there will be some backward incompatible changes, for example moving some 'backup_client' attributes to the common space like 'backup'.

**Comment by legal90** [comment]
I think this request could be closed, because DIY backup is already implemented (#68)

**Comment by linc01n** [comment]
Closing now
