### ISSUE TITLE
Missing mysql-chef_gem cookbook

### ISSUE THREAD

**Issue by linc01n** [bflad/chef-stash#69]
Since we didn't lock `database` cookbook, `database` cookbook version now is  4.0.1.

From 2.3.1 to 3.0.0 (https://github.com/opscode-cookbooks/database/compare/v2.3.1...v3.0.0#diff-9fd042d4cd1e8f82894bbd7dffb313ecL19), it changed the dependency of the cookbook.

Somehow running `vagrant provision centos6` in development it will throw error on  `could not find recipe mysql for cookbook database`

The fix is to lock the `database` version like this

`depends 'database', '~> 2.3.1'`

I will send a pull request soon.

related to #59

**Comment by patcon** [comment]
I think mysql2_chef_gem cookbook was just split out of the database cookbook, but that should be a pretty quick fix. Would be great to get to working with newer database cookbooks, as right now the very strict cookbook requirement is making berkshelf dependency resolution unhappy
