### ISSUE TITLE
Stash Crashes Due to java.lang.OutOfMemoryError PermGen Space Error

### ISSUE THREAD

**Issue by linc01n** [bflad/chef-stash#84]
I have this issue twice after I upgraded my Stash to 3.8.0 4 days ago. The solution is to increase

```ruby
default['stash']['jvm']['maximum_permgen'] = '256m'
```

I am still testing how many ram should I increase

From Stash Knowledge base:
> If you're experiencing this issue after upgrading to Stash 3.8+ and are using Java 7, it's likely that the setenv.sh (setenv.bat for Windows) was copied from a previous version. 

![screen shot 2015-04-24 at 11 43 32 am](https://cloud.githubusercontent.com/assets/667272/7312015/2b8bbe2e-ea77-11e4-917f-cba5a03882ff.png)

source: https://confluence.atlassian.com/display/STASHKB/Stash+Crashes+Due+to+java.lang.OutOfMemoryError+PermGen+Space+Error

**Comment by bflad** [comment]
Seems reasonable to me to change the settings based on the newer default configuration file.

**Comment by patcon** [comment]
Any objection to adding logic to the setenv.sh file to create a template correctly when 3.8+?

**Comment by mrjcleaver** [comment]
Sounds good to me :)
